### ISSUE TITLE
About the depth images 

### ISSUE THREAD

**Issue by myukzzz** [visinf/veto#3]
As mentioned in the article, you built the depth dataset with the AdelaiDepth tool, and the depth dataset is not currently in the repository, so the code is not available at this time, will you share the depth dataset you built later? Looking forward to your reply

**Comment by GopikaSudhakaran** [comment]
Hi, you could use the following link:
https://drive.google.com/file/d/13QKtd-ZjrG0K8mBsWk41notleQWSeeYz/view?usp=sharing
